/** The K³ logo (generated by scripts/generate_logo.py). It ships its own dark tile, so it reads on both themes. */
export function BrandMark({ size = 40, title, className }: { size?: number; title?: string; className?: string }) {
  return (
    // eslint-disable-next-line @next/next/no-img-element -- small static SVG from /public, nothing to optimize
    <img src="/brand/k3/logo-k3.svg" width={size} height={size} alt={title ?? ""} aria-hidden={title ? undefined : true} className={className} decoding="async" />
  );
}
